UWTest\Entity\User:
  type: entity
  oneToMany:
    messages:
      targetEntity: Message
      mappedBy: user
    like_given:
      targetEntity: LikeGiven
      mappedBy: user
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
